unqualified-search-registries = ["registry.access.redhat.com", "registry.redhat.io", "quay.io", "docker.io"]
short-name-mode = "enforcing"

[[registry]]
  location = "quay.io/openshift-release-dev"
  mirror-by-digest-only = false
  [[registry.mirror]]
    location = "quay.proxy.example.com/quayio_proxy/openshift-release-dev"

[[registry]]
  location = "registry.redhat.io"
  mirror-by-digest-only = false
  [[registry.mirror]]
    location = "quay.proxy.example.com/registry_redhat_proxy"
